"""create tables

Revision ID: 1b0c239ecc83
Revises: 
Create Date: 2024-11-29 17:15:21.009079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b0c239ecc83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_uid', sa.String(length=32), nullable=False),
    sa.Column('company_uuid', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('shop_cipher', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('channel_uid'),
    sa.UniqueConstraint('shop_cipher')
    )
    op.create_index(op.f('ix_channels_channel_uid'), 'channels', ['channel_uid'], unique=True)
    op.create_table('inventoryrequests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_uid', sa.String(length=32), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('feed_id', sa.String(length=16), nullable=True),
    sa.Column('request_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_uid'], ['channels.channel_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventoryrequests_id'), 'inventoryrequests', ['id'], unique=True)
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('access_token_expiry', sa.Integer(), nullable=False),
    sa.Column('refresh_token_expiry', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel'], ['channels.channel_uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_inventoryrequests_id'), table_name='inventoryrequests')
    op.drop_table('inventoryrequests')
    op.drop_index(op.f('ix_channels_channel_uid'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
